"use client";
import { FormEvent, useEffect, useState } from "react";
import { MessageRow, supabase } from "../../lib/supabase";
type AdminMessage=MessageRow&{image?:string};
export default function AdminPage(){
 const[authenticated,setAuthenticated]=useState(false),[messages,setMessages]=useState<AdminMessage[]>([]),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{void supabase.auth.getSession().then(({data})=>{const ok=data.session?.user.app_metadata?.role==="admin";setAuthenticated(ok);if(ok)void loadMessages()})},[]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError("");const{data,error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError||data.user?.app_metadata?.role!=="admin"){await supabase.auth.signOut();setError("Tài khoản không có quyền admin.");setBusy(false);return}setAuthenticated(true);setBusy(false);void loadMessages()}
 async function loadMessages(){const{data,error:queryError}=await supabase.from("messages").select("*").order("created_at",{ascending:false});if(queryError){setError("Không thể tải danh sách kiểm duyệt.");return}const rows=await Promise.all((data as MessageRow[]).map(async row=>{if(!row.image_path)return row;const{data:signed}=await supabase.storage.from("message-images").createSignedUrl(row.image_path,3600);return{...row,image:signed?.signedUrl}}));setMessages(rows)}
 if(!authenticated)return <main className="admin-page"><section className="admin-login"><h1>GUESTBOOK ADMIN</h1><p>Đăng nhập bằng tài khoản admin Supabase.</p><form onSubmit={login}><input type="email" required placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<div className="admin-error">{error}</div>}<button className="primary" disabled={busy}>{busy?"Đang đăng nhập…":"Sign in"}</button></form></section></main>;
 return <main className="admin-page"><div className="admin-shell"><header className="admin-header"><div><h1>ALL MESSAGES</h1><p>{messages.length} lời chúc · Chế độ chỉ xem, không thể xóa</p></div><button onClick={async()=>{await supabase.auth.signOut();setAuthenticated(false)}}>Sign out</button></header>{error&&<p className="admin-error">{error}</p>}<section className="admin-grid">{messages.length===0&&<div className="admin-empty">Chưa có lời chúc nào.</div>}{messages.map(m=><article className="admin-card" key={m.id}><div><small>{new Date(m.created_at).toLocaleString("vi-VN")}</small><h3>{m.sender_name}</h3>{m.content&&<p>{m.content}</p>}{m.image&&<img src={m.image} alt="Ảnh lời chúc"/>}</div></article>)}</section></div></main>}
